'use strict';

// Environment variable names — see backend/.env.example. src/config/index.js references these
// instead of repeating the literal env var names anywhere they're needed outside the schema itself.

module.exports = Object.freeze({
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  HOST: 'HOST',
  LOG_LEVEL: 'LOG_LEVEL',
  CORS_ALLOWED_ORIGINS: 'CORS_ALLOWED_ORIGINS',
  PUBLIC_BASE_URL: 'PUBLIC_BASE_URL',

  FIREBASE_PROJECT_ID: 'FIREBASE_PROJECT_ID',
  FIREBASE_CLIENT_EMAIL: 'FIREBASE_CLIENT_EMAIL',
  FIREBASE_PRIVATE_KEY: 'FIREBASE_PRIVATE_KEY',
  FIREBASE_DATABASE_URL: 'FIREBASE_DATABASE_URL',
  FIREBASE_STORAGE_BUCKET: 'FIREBASE_STORAGE_BUCKET',

  OPENROUTER_API_KEY: 'OPENROUTER_API_KEY',
  OPENROUTER_BASE_URL: 'OPENROUTER_BASE_URL',
  DEFAULT_MODEL: 'DEFAULT_MODEL',
  OCR_PROVIDER_API_KEY: 'OCR_PROVIDER_API_KEY',

  SURFBOARD_API_KEY: 'SURFBOARD_API_KEY',
  SURFBOARD_API_SECRET: 'SURFBOARD_API_SECRET',
  SURFBOARD_WEBHOOK_SECRET: 'SURFBOARD_WEBHOOK_SECRET',
  SURFBOARD_ENV: 'SURFBOARD_ENV',
  SURFBOARD_AUTH_STRATEGY: 'SURFBOARD_AUTH_STRATEGY',
  SURFBOARD_BEARER_TOKEN: 'SURFBOARD_BEARER_TOKEN',
  SURFBOARD_PARTNER_ID: 'SURFBOARD_PARTNER_ID',
  SURFBOARD_API_URL: 'SURFBOARD_API_URL',
  SURFBOARD_SECRET_KEY: 'SURFBOARD_SECRET_KEY',
  SURFBOARD_ONLINE_STORE_WEBSHOP_URL: 'SURFBOARD_ONLINE_STORE_WEBSHOP_URL',
  SURFBOARD_ONLINE_STORE_TERMS_URL: 'SURFBOARD_ONLINE_STORE_TERMS_URL',
  SURFBOARD_ONLINE_STORE_PRIVACY_URL: 'SURFBOARD_ONLINE_STORE_PRIVACY_URL',
});
