'use strict';

// Environment variable names — see backend/.env.example. src/config/index.js references these
// instead of repeating the literal env var names anywhere they're needed outside the schema itself.

module.exports = Object.freeze({
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  LOG_LEVEL: 'LOG_LEVEL',
  CORS_ALLOWED_ORIGINS: 'CORS_ALLOWED_ORIGINS',

  FIREBASE_PROJECT_ID: 'FIREBASE_PROJECT_ID',
  FIREBASE_CLIENT_EMAIL: 'FIREBASE_CLIENT_EMAIL',
  FIREBASE_PRIVATE_KEY: 'FIREBASE_PRIVATE_KEY',
  FIREBASE_DATABASE_URL: 'FIREBASE_DATABASE_URL',
  FIREBASE_STORAGE_BUCKET: 'FIREBASE_STORAGE_BUCKET',

  GEMINI_API_KEY: 'GEMINI_API_KEY',
  OCR_PROVIDER_API_KEY: 'OCR_PROVIDER_API_KEY',

  SURFBOARD_API_KEY: 'SURFBOARD_API_KEY',
  SURFBOARD_API_SECRET: 'SURFBOARD_API_SECRET',
  SURFBOARD_WEBHOOK_SECRET: 'SURFBOARD_WEBHOOK_SECRET',
  SURFBOARD_ENV: 'SURFBOARD_ENV',
  SURFBOARD_AUTH_STRATEGY: 'SURFBOARD_AUTH_STRATEGY',
  SURFBOARD_BEARER_TOKEN: 'SURFBOARD_BEARER_TOKEN',
});
